# Generated by Django 5.1.4 on 2025-04-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed_detections/')),
                ('detection_type', models.CharField(choices=[('shelf', 'Shelf Image'), ('checkout', 'Checkout Image')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detection_data', models.TextField()),
                ('session_id', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
