# Generated by Django 5.1.4 on 2025-04-05 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_roomactivity'),
        ('yolo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detection',
            name='staff_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staffmember'),
        ),
        migrations.AlterField(
            model_name='detection',
            name='detection_type',
            field=models.CharField(choices=[('checkin', 'Check-in Image'), ('checkout', 'Check-out Image')], max_length=10),
        ),
    ]
