# Generated by Django 5.1.4 on 2025-04-05 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_room_roominventory'),
        ('staff', '0003_roomactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomactivity',
            name='added_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomactivity',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.room'),
        ),
        migrations.AddField(
            model_name='roomactivity',
            name='shifted_items',
            field=models.TextField(blank=True, null=True),
        ),
    ]
