# Generated by Django 5.1.4 on 2025-04-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_roomactivity_added_items_roomactivity_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomactivity',
            name='approved_items',
            field=models.TextField(blank=True, help_text='JSON list of items that have been manually marked as OK', null=True),
        ),
    ]
