# Generated by Django 5.1.4 on 2025-04-05 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_roomactivity_approved_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('checkin_image', models.ImageField(blank=True, null=True, upload_to='checkout_analysis/originals/checkin/')),
                ('checkout_image', models.ImageField(blank=True, null=True, upload_to='checkout_analysis/originals/checkout/')),
                ('yolo_result', models.TextField(blank=True, help_text='JSON data from YOLO object detection comparison', null=True)),
                ('spatial_analysis_result', models.TextField(blank=True, help_text='JSON data from spatial analysis', null=True)),
                ('feature_matching_result', models.TextField(blank=True, help_text='JSON data from feature matching', null=True)),
                ('color_histogram_result', models.TextField(blank=True, help_text='JSON data from color histogram analysis', null=True)),
                ('heatmap_result', models.TextField(blank=True, help_text='JSON data from heatmap analysis', null=True)),
                ('damage_detection_result', models.TextField(blank=True, help_text='JSON data from damage detection analysis', null=True)),
                ('yolo_visualization', models.ImageField(blank=True, null=True, upload_to='checkout_analysis/visualizations/yolo/')),
                ('spatial_visualization', models.ImageField(blank=True, null=True, upload_to='checkout_analysis/visualizations/spatial/')),
                ('feature_matching_visualization', models.ImageField(blank=True, null=True, upload_to='checkout_analysis/visualizations/feature_matching/')),
                ('color_histogram_visualization', models.ImageField(blank=True, null=True, upload_to='checkout_analysis/visualizations/color_histogram/')),
                ('heatmap_visualization', models.ImageField(blank=True, null=True, upload_to='checkout_analysis/visualizations/heatmap/')),
                ('damage_visualization', models.ImageField(blank=True, null=True, upload_to='checkout_analysis/visualizations/damage/')),
                ('summary_result', models.TextField(blank=True, help_text='JSON summary of all analysis methods', null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Overall confidence score for the analysis')),
                ('simple_summary', models.TextField(blank=True, help_text='Simple human-readable summary of the analysis', null=True)),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations based on the analysis', null=True)),
                ('room_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_analyses', to='staff.roomactivity')),
            ],
            options={
                'verbose_name_plural': 'Checkout Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
