# Generated by Django 5.1.4 on 2025-04-05 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_checkoutanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisplacedItemsAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('checkin_image', models.ImageField(blank=True, null=True, upload_to='misplaced_analysis/images/checkin/')),
                ('checkout_image', models.ImageField(blank=True, null=True, upload_to='misplaced_analysis/images/checkout/')),
                ('visualization', models.ImageField(blank=True, null=True, upload_to='misplaced_analysis/visualizations/')),
                ('gemini_analysis', models.TextField(blank=True, help_text='Raw analysis text from Gemini AI', null=True)),
                ('structured_analysis', models.TextField(blank=True, help_text='JSON structured analysis data', null=True)),
                ('room_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misplaced_analyses', to='staff.roomactivity')),
            ],
            options={
                'verbose_name_plural': 'Misplaced Items Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
