# Generated by Django 5.1.4 on 2025-04-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_misplaceditemsanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='misplaceditemsanalysis',
            name='cleanliness_assessment',
            field=models.TextField(blank=True, help_text='Detailed cleanliness assessment', null=True),
        ),
        migrations.AddField(
            model_name='misplaceditemsanalysis',
            name='cleanliness_score',
            field=models.FloatField(default=0.0, help_text='Overall cleanliness score (0-100)'),
        ),
        migrations.AddField(
            model_name='misplaceditemsanalysis',
            name='repair_assessment',
            field=models.TextField(blank=True, help_text='Assessment of repairs needed', null=True),
        ),
        migrations.AddField(
            model_name='misplaceditemsanalysis',
            name='repair_cost_estimate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Estimated repair costs', max_digits=10),
        ),
        migrations.AddField(
            model_name='misplaceditemsanalysis',
            name='repair_items',
            field=models.TextField(blank=True, help_text='JSON data of repair items with costs', null=True),
        ),
    ]
